#
#P ROGRAM: sorting
# AUTHOR:  Mohamed Sharif
#

CXXFLAGS+=-Wall -Werror -std=c++11

PROGS=bubble_sort selection_sort insertion_sort

.PHONY: all clean world

all: $(PROGS)

clean:
	rm -f *.o $(PROGS)

world: clean all
